Make website_cache_control not installable I made this module not installable because it's not working correctly, and we're not using it anyways:
2024-03-07 13:29:34,956 23 ERROR bd75cefeb-47fe-45ff-88be-36b4d1ce5578 odoo.http: Exception during request handling.
Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 2044, in __call__
    response = request._serve_db()
  File "/opt/odoo/odoo/http.py", line 1633, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/opt/odoo/odoo/http.py", line 1660, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo/odoo/http.py", line 1774, in dispatch
    return self.request.registry['ir.http']._dispatch(endpoint)
  File "/mnt/data/odoo-addons-dir/website_cache_control/models/ir_http.py", line 43, in _dispatch
    response.set_cookie("odoo_backend", request.httprequest.session.sid)
  File "/opt/odoo/odoo/http.py", line 1022, in getter
    return getattr(self._HTTPRequest__wrapped, attr)
AttributeError: 'Request' object has no attribute 'session'